g4klx/MMDVM

- BUILD.txt
Just added a few lines about compiling on Linux and also where the sam/platform.txt may be located if the library manager installs it automatically.
> More info on Linux & newer libraries OK

- Config.h
- IOSTM.cpp
New PTT port PA6 and more conditional compile for RSSI
> Some minor changes

- mmdvmmenu.sh
Some minor correction of typos and added the option for 12.288 MHz TCXOs.
> Added 12.288MHz TCXO to mmdvmmenu.sh

- IOTeensy.cpp
> Correct calibration

- IOTeensy.cpp
Added some comments from CPU documentation to understand the code.
> Add some comments

- DMRDMOTX.h
Same fix as applied to master branch.
> Fix crash in DMO Mode

- IOSTM.cpp
- SerialSTM.cpp
See https://twitter.com/flo_0_/status/822082944898650116
@juribeparada Ok?
> Refactored STM code concerning whitespace

- .gitignore
Get rid of useless git status messages
> Add gitignore to irgnore object files and STM lib

- DMRDMOTX.cpp
- DMRDMOTX.h
- DMRTX.cpp
- DMRTX.h
- DStarTX.cpp
- DStarTX.h
- P25TX.cpp
- P25TX.h
- YSFTX.cpp
- YSFTX.h
Using arm_fir_interpolate_q15() function of CMSIS is efficient
> Using CMSIS FIR interpolator for all modulators

- DMRDMOTX.cpp
- DMRTX.cpp
This is only for DMR. Next I will add for other modes.
> Compensate DMR deviation to match old adjustments

- IOSTM_CMSIS.cpp
Fancy animation for testing LEDs when powering up.
> Starting LED animation for MMDVM_pog board

- IOSTM_CMSIS.cpp
Pull Request put the USART used back to USART2. Should be USART1
73, Steve N4IRS
> Fix USART2 to USART1 after PR 94

- Makefile.Arduino
See issue https://github.com/g4klx/MMDVM/issues/95
This should fix it. 
@m1geo Could you pls verify?
> Fix Arduino Makefile to include GitVersion on upload

- IO.cpp
- IO.h
- IOSTM.cpp
- SerialPort.cpp
- SerialSTM.cpp
This fix modem no response problem, specially when serial port repeater (Nextion) is enabled and reboot MMDVMHost (this happen very often with Nucleo-64 boards).
> Adding watchdog to host serial port

- IO.cpp
- IO.h
I still have to add SINC filter for TX and check deviation
> Add inverse SINC filter for NXDN demodulator

- P25TX.cpp
- P25TX.h
Now this filter is according with the shaping filter specifications of TIA-102.BAAA-A
> Fixing inverse SINC TX filter for P25

- IOSTM.cpp
Pin definition in comment was off by 1
> Fix comments for STM32-DVM Rev 3

- SerialPort.cpp
At least a way to have that in the modem description string. If anyone encounters an easier way instead of doubling the code here I am happy to learn :)
> Add TCXO frequency to modem description

- SerialPort.cpp
> Add description for non TCXO systems

- Config.h
- I2CTeensy.cpp
- SerialArduino.cpp
Adding support for VK6MST Pi3 sheild to use i2c communication with RaspberryPi.
> Add support for VK6MST_Shield

- Makefile
Fixed issues with flashing MMDVM-Pi when using make deploy-pi-f7
> Fixed deploy-pi-f7

- FM.cpp
- FMCTCSSRX.cpp
- FMCTCSSRX.h
Change CFM::Samples and CFMCTCSSRX::process to be able to process all
stuff in one and only loop.
> One loop to rule them all !

- FM.cpp
- FM.h
- FMCTCSSRX.cpp
- FMDirectForm1.h
- FMGenerateFilterCoefficients.py
This adds own FM filtering and a python script to generate coefficients if needed.
> Add FM Filtering

- FMCTCSSRX.cpp
- IO.cpp
- IO.h
> Revert "Make CTCSS threshold RXLevel and RXBoost agnostic"

- FMCTCSSTX.cpp
This should fix the arm_sin_q15 crashing on certain platforms
> Fix invalid values passed to arm_sin_q15

- CalFM.cpp
- CalFM.h
- Globals.h
- MMDVM.cpp
- MMDVM.ino
- MMDVM_STM32F4xx.coproj
- SerialPort.cpp
Here is the code for FM calibration modes, i'm not convinced that the frequencies are exactly correct though!
> Add FM Cal modes

- CalFM.cpp
Change FM cal level to better match the actual repeater.
> Change FM cal levels

- FM.cpp
- Tools/emphasis.txt
> Revert "Change emphasis time constant to 750µS"

- FM.cpp
- FM.h
- FMSamplePairPack.h
- FMUpSampler.cpp
- FMUpSampler.h
- Fix crash when writing to serial
- Tighten handling of incoming data, move upsampling to separate class
> Fix crash when writing to serial, Tighten handling of incomign data

- SerialPort.cpp
Forgot to commit this file yesterday, sorry
> Add forgotten file for large frame handling

- SerialSTM.cpp
> Add STM32F7-DVM board
