g4klx/MMDVM

BUILD.txt
Updated with Linux information tested on Ubuntu.
Had to install sam-1.6.6 myself, download from ttp://downloads.arduino.cc/cores/sam-1.6.6.tar.bz2 and extract to arduino-1.6.7/hardware/arduino/
Modify platform.txt as with Windows/OSX, but path changes slightly from ARM to GCC: "{build.system.path}/CMSIS/CMSIS/Lib/GCC/libarm_cortexM3l_math.a"
=> Updated BUILD.txt for Linux

CalDMR.cpp, CalDMR.h, DMRTX.cpp, DMRTX.h, Globals.h, MMDVM.ino, SerialPort.cpp
Add new mode for DMR Deviation Calibration.
Using MMDVMCal a new keyboard command 'D' puts modem into DMR test mode. 
'd' returns to Dstar mode. 
As defined in ETSI TS102 361-1 para. 10.2.2.3 this allows DMR deviation to be set using conventional 
FM deviation meters. 
The DMR Tx stream is constantly fed with +3+3-3-3 which after filtering produces a 1200Hz sinewave. 
The deviation of this sinewave should be set to 2.749 Khz +-10%.
=> Add new Mode for DMR Deviation Calibration.

BUILD.txt
I added some information and the latest Arduino IDE. Maybe we should consider deletion of information about older Arduino IDE versions?
=> Add information for MMDVM build on Ubuntu 14.04 with latest Arduino IDE

SerialPort.cpp
I guess it might be helpful if the information coming from MMDVM during initialization contained a hint about if the firmware was compiled with external oscillator enabled.
=> Add hint about if MMDVM was compiled with EXTERNAL_OSC

Config.h
Referencing the discussion in MMDVM Yahoo group under https://groups.yahoo.com/neo/groups/mmdvm/conversations/topics/8735
It seems that some people couldn't use MMDVM firmware because TCXO with 12MHz was enabled by default in commit f8d9c881. I guess this was an accident and the TCXO should be left defaulting to off.
=> Disable external TCXO by default

Config.h, mmdvmmenu.sh
For some reason the defines for MMDVM board contain two spaces just before the board name. That break functionality of mmdvmmenu.sh
=> Correct spaces in order to make mmdvmmenu.sh work (again)

Config.h
I think EXTERNAL_OSC must be disabled by default, for Due MMDVM without TCXO support.
=> EXTERNAL_OSC enabled by default?

SerialPort.cpp
I have come to the conclusion that the getStatus() function reports incorrect length of reply array. The value was probably not aligned when P25 was added. Just stumbled across this while trying to debug a feature I was developing. Not a real big problem but it has taken me some time ... :-)
=> Fix length of reported parameters

Globals.h, IO.cpp, IO.h, MMDVM.cpp, MMDVM.ino, SerialPort.cpp
Added one more LED to let the UMP be able  to signalize when MMDVMHost detected a valid carrier. The information is hooked from the MMDVM CD function that also drives the ZUM onboard LED.
=> Add carrier detect LED to MMDVM firmware

IOTeensy.cpp
External TCXO was not working with Pre-Trigger set to B.
This change sets it to A which appears to work.
=> Adjust ADC pre-trigger setting for external TCXO

IOTeensy.cpp
Disable interrupts for ADC1. 
Every time ADC0 interrupts (24Khz) read the current conversion from ADC1 and software trigger a new one. 
This way there will always be an ADC1 conversion available whenever ADC0 interrupts.
=> Change ADC1 to reduce number of interrupts.

DMRDMOTX.h
Modem was crashing on Teensy when running in DMO mode. Crashed as soon as Tx started. Traced to exceeding the bounds of m_poBuffer during the txdelay phase.
m_poBuffer was dimensioned to 80 but m_txdelay could be 600 to 1200 so a massive overwrite was happening.
Surprisingly this didn't crash on the Due only on the Teensy. However it applies to both.
=> Fix crash in DMR DMO Mode on Teensy

.gitignore, Config.h, Globals.h, IOSTM_CMSIS.cpp, MMDVM.cpp, Makefile.CMSIS, RSSIRB.h, RingBuff.h, STM32Utils.h, SampleRB.h, SerialRB.h, SerialSTM_CMSIS.cpp, Utils.h, openocd.cfg, system_stm32f1xx/gcc.ld, system_stm32f1xx/startup_stm32f105xc.S, system_stm32f1xx/system_stm32f1xx.c
MMDVM_pog board project is available [here](https://github.com/wojciechk8/MMDVM_pog). I've added support for this board using pure CMSIS driver (without HAL or Standard Peripheral Library from STM). Moreover I've included Makefile, which enables to build the firmware for this MCU (additional requirements are given on the project site).
Compilation size report (STM32F105RBT has 128kB flash and 64kB RAM):
| text  | data | bss   | dec   | hex   | filename      |
|-------|------|-------|-------|-------|---------------|
| 42004 | 1476 | 36416 | 79896 | 13818 | bin/mmdvm.elf |
=> Adding support for STM32F1 MCU and MMDVM_pog board

.gitignore, Makefile, SerialPort.cpp
At least for MMDVMs built via Makefile (e.g. STM32F446RE nucleo board) include the GitID of the running firmware.
=> Include Git ID in Modem description

SerialPort.cpp
Fixes a warning while using the original Arduino IDE:
=> Remove Arduino compiler warning

Makefile
According to the discussion in MMDVM Yahoo group, my last commits broke Windows builds.
This should fix it. Feedback welcome.
=> Make Makefile compatible with builds on Windows

IOSTM_CMSIS.cpp, Makefile.CMSIS, SerialSTM_CMSIS.cpp
In revision 1.0 of MMDVM_pog board I moved host communication port to USART1 (PA9, PA10), so now it's possible to program the microcontroller via internal bootloader, as it was supposed to be.
=> MMDVM_pog revision 1.0 changes

IOSTM.cpp
Seems like some people haver problems finding the proper pins on STM boards. This enhances the comment section a bit in order to prevent from manufacturing non-working PCBs.
=> Added some more description on pinouts of STM

DMRDMORX.cpp, DMRSlotRX.cpp, DStarRX.cpp, DStarRX.h, Globals.h, IO.cpp, IO.h, MMDVM.cpp, MMDVM.ino, P25RX.cpp, SerialSTM.cpp, YSFRX.cpp
It could be useful in some cases where a DC offset is present in DMR for example, and difficult the initial detection (RF late entry...). Tested with Due (no problem with computational processing) and STM32F446.
=> DC estimator filter for all modes

YSFRX.h
Fixes warning about order of initialization mentioned in Yahoo group by dm112179
=> Refactor variable initialization in YSFRX.h

IOSTM_CMSIS.cpp
Fix undefined reference to `CIO::delayInt(unsigned int)' for LED test
=> Fix undefined reference

Makefile.Arduino
As @marrold noted: The .bin file created my Makefile should be available after executing "make -f Makefile.Arduino compile". Up to now it was only created when executing "make -f Makefile.Arduino upload".
=> Create .bin on compile target instead of upload

DStarRX.cpp
Hi,
We have been playing around with the DStar_corellator since a few days. Early tests showed that it is capable of decoding very low signals but is dropping signal on stations with fading. Analysis showed that the MMDVM is seeing erroneous end sync frames. Lowering END_SYNC_ERRS to 1 solves the issue, the only minor side effect is that if the actual end frame got missed the MAX_FRAMES timeout kicks in and you get 150 frames of R2D2. I am thinking of also lowering this value, btw.
73
Geoffrey F4FXL / KC3FRA
=> Fixes erroneous end sync on stations having QSB

DStarRX.cpp
Hi,
We have been playing around with the DStar_corellator since a few days. Early tests showed that it is capable of decoding very low signals but is dropping signal on stations with fading. Analysis showed that the MMDVM is seeing erroneous end sync frames. Lowering END_SYNC_ERRS to 1 solves the issue, the only minor side effect is that if the actual end frame got missed the MAX_FRAMES timeout kicks in and you get 150 frames of R2D2. I am thinking of also lowering this value, btw.
73
Geoffrey F4FXL / KC3FRA
=> Fixes erroneous end sync seen on station having QSB

IOSTM_CMSIS.cpp
Fix for STM32-DVM and MMDVM_POG always reporting the same value for RSSI. 
ADC sampling was never being triggered for the RSSI pin.
=> STM32-DVM & MMDVM_POG RSSI bugfix

DStarRX.cpp
Fix for "false end of transmission" during D-Star RX
=> Reducing the bit error number for the EOT sequence (D-Star)

Config.h, IO.cpp
Adds a compile time option in Config.h  to make the service LED constant as opposed to rapidly blinking.
Adds a note to Config.h to say not to use this if using an external hardware watchdog.
=> Constant Service LED

FMCTCSSTX.cpp, FMKeyer.cpp
In the new FM branch, I noticed that every time I restarted MMDVMHost without rebooting the MMDVM, the callsign and ack  was added to the existing rather than replacing them. 
The simple fix was to set m_poLen = 0 at the beginning of setParams() in FMKeyer.cpp as otherwise subsequent calls to setParams() start at the end of any current data.
I also noticed that each invocation of setParams() will create a new m_audio array, which I suspect causes a memory leak so I have added a delete[]. The same function in FMCTCSSTX.cpp also has this issue I think.
=> Fix for Ack/Callsign corruption in FM branch

FMCTCSSRX.cpp, IO.cpp, IO.h
CTCSS Thresold now RX level independent, however larger values are needed in the config. E.g. I had 30 and needed 80 with this change.
=> CTCSS threshold is level agnostic

FM.cpp, FM.h, FMCTCSSRX.cpp, FMCTCSSRX.h
This uses division as implementing binary longdivision would have involved lots of loops and conditions.
ARM-v7M has  [hardware divsion](https://developer.arm.com/ip-products/processors/cortex-m/cortex-m3)
=> Make the FM chain RX Level independant

IOSTM.cpp
Also adds the missing FM led/mode GPIO init code.  Currently only the "MMDVM_RPT_Hat Pi-Hat F0DEI DB9MAT DF2ET board" supports dedicated FM led/mode pins.
=> Fix led alternate macro names

Config.h, FM.cpp, FMDirectForm1.h, FMDownsampler.cpp, FMDownsampler.h, FMUpSampler.cpp, STMUART.cpp, STMUART.h, SerialPort.cpp, SerialPort.h, SerialSTM.cpp, Tools/FMGenerateFilterCoefficients.py
- improve IO.buffer filling from FM::process
- Clean up STM UART copy paste code
- Add compile options for serial speed, if not defined defaults to 115200
- Improve filter generation script
- Fix sample packing
=> Speed improvements and fixes for FM Ext

IO.cpp, pins/pins_f4_stm32eda.h
In anticipation of a new hardware revision with additional mode LEDs, a pin definition for an FM mode LED was assigned.
=> Added pin definition for FM mode LED (WA0EDA Boards)

YSFRX.cpp
Lower MAX_SYNC_FRAMES to 2, so decoder can recover and Yaesu pictures can pass through the modem without problem.
=> YSF pictures can go through modem 

IODue.cpp
'status' was not declared in this scope and the register EFC is named EFC1 also IFLASH1_ADDR.
I add the flag wait loop in the beginning.
=> Fixing Arduino UUID support

IODue.cpp
Should we read the Unique Identifier in the same order as the example Code?
And is my Fix the right Way to do it?
=> Fixing Arduino Unique Identifier byte order

DStarRX.cpp, DStarRX.h
While testing new support for DV Fast Data in https://github.com/g4klx/MMDVMHost/pull/667, I ran across a particular image that reliably generated a bit sequence that the MDMVM firmware interpreted as an end-of-transmission.  I dug a bit and discovered that MMDVM only matches on 32 bits of the last data frame instead of the full 48 bits.
(I referenced http://www.arrl.org/files/file/D-STAR.pdf section 2.1.2, item (6))
I'm not convinced that this implementation is the best version of this change, but it does work for me.  I tested this patch on both a ZUMSpot (by making the same change against https://github.com/juribeparada/MMDVM_HS) and a Raspberry Pi with a ZUM Radio MMDVM-Pi rev 1.0 board, and the test image no longer generated an early EOT on either system.
=> Detect full 48 bits of last data frame in a D-Star transmission

pins/pins_f7_stm32dvm_v5.h
File mentioning used pins on STM32F7 DVM had a typing error saying pinout is for STM32F4, added PB15 - FM LED output to the comment with all used pins.  Pin is defined in following lines but not mentioned in the comment with all the pins.
=> Added PB15 to comment with pins, changed STM32F4 to STM32F7 in line 23

AX25TX.cpp
The AX25 sine value ranges from 0-4095, and inside io.write() will perform the calculation (value * q15_t(txLevel) >> 15) which may exceed 4096 and cause the DAC Overflow error
=> Fix AX25 DAC overflow error message

SerialPort.cpp
I noticed the position for Version 2 Status didn't allow for the POCSAG Size to be read correctly by MMDVMHost. I thought it is easier to provide a fix in the MMDVM firmware to get it working, given the use in pi-star etc.
Tested on my MMDVM and was able to receive POCSAG pager messages to my test pager. 
Cheers,
VK3PMR - Jason
=> Fixed Serial protocol issue where MMDVMHost could not send POCSAG or AX25 to the MMDVM

Config.h, pins/pins_f4_stm32eda.h
Adding a (commented) section in Config.h compile for 500000 UART speed to support the WA0EDA MODEMs and others that use Armbian + AllWinner H2/H3 SOC that does not support 4600800.
Adding support for FM LED on the WA0EDA STM-DVM-MTR2K v2.0d
=> WA0EDA STM32-DVM-MTR2K v2.0d FM LED -and- Armbian + AllWinner H2/H3 UART speed

Config.h, SerialPort.cpp
Existing code was hard coded to set the serial repeater baud rate to 9600.  This code change adds a SERIAL_REPEATER_BAUD_RATE define in the Config.h file, and sets the serial repeater baud rate to that user definable speed.  This will allow a 115,200 baud rate to be set for those using HS Nextion screen layouts that require the higher baud rate.
=> Added option to configure Serial Repeater baud rate 
